printWidth: 120
bracketSpacing: true
singleQuote: true
semi: true
overrides:
  - files: "*.ts"
    options:
      tabWidth: 2
  - files: "*.js"
    options:
      tabWidth: 2
  - files: "*.tsx"
    options:
      tabWidth: 2
  - files: "*.jsx"
    options:
      tabWidth: 2
  - files: "*.html"
    options:
      tabWidth: 2
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
      singleQuote: false
