parser: "@typescript-eslint/parser"
root: true

parserOptions:
  # project: "tsconfig.json"
  sourceType: "module"
  ecmaVersion: 2022

ignorePatterns:
  - "**/*.ts"


extends:
  - "plugin:@typescript-eslint/recommended"
  # - "plugin:prettier/recommended"

rules:
  "@typescript-eslint/no-empty-interface": off
